```{r}
googlesheets4::gs4_deauth()
googlesheets4::read_sheet(
  "https://docs.google.com/spreadsheets/d/1N6HBFe7_pNEiwgAdT5gWH86ytMx0-kYOXZZ29QHt4O0/edit?usp=sharing"
) -> 新北扶幼比
```

```{r}
plot=Plot(新北扶幼比)
head(plot$data)
```

```{r}
plot$ggplot=ggplot(data=plot$data)
```

```{r}
date = 新北扶幼比$年
data = list()
data$新北市 <- 
  data.frame(
    date = date,
    y = 新北扶幼比$新北市
  )
data$板橋區 <- 
  data.frame(
    date = date,
    y = 新北扶幼比$板橋區
  )
data$樹林區 <- 
  data.frame(
    date = date,
    y = 新北扶幼比$樹林區
  )

data$鶯歌區 <- 
  data.frame(
    date = date,
    y = 新北扶幼比$鶯歌區
  )


plot = Plot(data=date)

```

```{r}
data$新北市$扶幼比 = "新北市"
data$板橋區$扶幼比 = "板橋區"
data$樹林區$扶幼比 = "樹林區"
data$鶯歌區$扶幼比 = "鶯歌區"

dataAll = dplyr::bind_rows(
data$新北市,data$板橋區,data$樹林區,data$鶯歌區)
  
plot$dataAll = dataAll
```

```{r}
library(ggplot2)
plot$ggplot = ggplot(data=plot$dataAll,mapping=aes(
  x=date, y=y
))
plot$geoms = list(
  geom_line(
    mapping=aes(color=扶幼比),
    size=2.5
  )
)

plot$explain = list(
  labs(
    title="新北市各區扶幼比變化",
    subtitle="扶幼比=(0-14歲人口)/(15-64歲人口)*100",
    caption="資料來源:中華民國統計資訊網"
  ),xlab(NULL)
  )


plot$ggplot+plot$geoms+plot$explain
```

